### ISSUE TITLE
Create app or component to query urlscan.io

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/threatconnect-playbooks#104]
It would be great to have a playbook/component to query urlscan.io (https://urlscan.io/about-api/#search).

**Comment by brikardtc** [comment]
This is available here: https://github.com/ThreatConnect-Inc/threatconnect-playbooks/tree/master/components/TCPBC-Submit%20to%20URLscan

**Comment by fhightower** [comment]
@brikardtc , thanks for the response, but the component you mentioned is for _submitting_ a url to urlscan.io. This issue suggests a component to use urlscan.io's _search_ api which doesn't require an API key (described here: https://urlscan.io/about-api/#search) (e.g. https://urlscan.io/api/v1/search/?q=domain:urlscan.io").

**Comment by richardcody** [comment]
@fhightower I've gone ahead and created an official urlscan.io Search component and added it to App Catalog that can be accessed inside the ThreatConnect Platform. Let me know if you have any issues!
