### ISSUE TITLE
CIDR Range Utility: 

### ISSUE THREAD

**Issue by wsummerhill** [ThreatConnect-Inc/threatconnect-playbooks#114]
Do you have any resources to view on how to import these apps into TC? Thanks!

**Comment by paulh-tc** [comment]
@wsummerhill  Here's how to install apps on your ThreatConnect platform. Note this applies for Dedicated Cloud or On-Premise deployments:

1. Log in with a System Admisistrator account.
2. On the top navigation bar place the cursor on the **Settings** (cogwheel) icon and the Settings menu will appear. Select **TC Exchange Settings**.
3. Click the **Install App** + button to the upper right of the screen, and the Install App pop-up screen will appear.
4. Click the **+ SELECT FILE** button, and navigate to the zipped app file.
5. Verify that the information in the App Name and Type fields is correct, and then click the **INSTALL** button.
6. The app will now appear in the Installed Apps list.
